title: "Athena Zhang"
description: "Analytics portfolio"
url: "https://ry979.github.io"  
baseurl: ""                     

minimal_mistakes_skin: dirt
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache

author:
  name: "Athena Zhang"
  avatar: "/assets/images/profile.jpg"
  bio: "Northeastern '25"
  location: "Boston, MA"
  links:
    - label: "CV"
      icon: "fas fa-link"
      url: "/assets/docs/cv2.pdf"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:Athenaruiyu.zhang@outlook.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/athena-zhang-49778a263/"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/athena_ruiyu/"
